### DISCUSSION TITLE
Welcome to TopoStats Discussions!

### DISCUSSION THREAD

**Discussion by bobturneruk** [AFM-SPM/TopoStats#39] [General]
## 👋 Welcome!

We’re using Discussions as a place to connect with other members of our community. We hope that you:

- Ask questions you’re wondering about.
- Share ideas.
- Engage with other community members.
- Welcome others and are open-minded. Remember that this is a community we build together 💪.
- **If you have questions about using TopoStats please start a new thread** or consider creating a new [Issue](https://github.com/AFM-SPM/TopoStats/issues/new/choose).

**Comment by jrobert21** [comment]
Hi everyone, 

Thank you to all those who have worked on this software. I'm conducting a summer research project involving AFM imaging and DNA measurements. My project has a lot of images involved and many DNA fragments so an automated measurement software would be fantastic. I'm very new to python and was wondering if there was an installation guide or tutorial for implementing TopoStats for use in my project? Thanks again.

**Reply by bobturneruk** [reply]
Hi @jrobert21! There's some stuff here https://github.com/AFM-SPM/TopoStats/issues/10 not sure if it's 100% reliable. I belive a proper install guide is on its way. @Jean-Du may be able to say more. There's also a potential way forward with docker (if you're into that sort of thing) https://github.com/AFM-SPM/TopoStats/pull/44.

**Reply by Jean-Du** [reply]
Hi here is an installation guide for using TopoStats with PyCharm in Windows
[Importing gwy in PyCharm.pdf](https://github.com/AFM-SPM/TopoStats/files/6755340/Importing.gwy.in.PyCharm.pdf)

**Comment by ankushDhawan5812** [comment]
Hello!

My name is Ankush Dhawan, and I am a researcher in the Mai Group at Stanford University working on imaging DNA in confinement. I came across your work when working on image processing. I wanted to test out Topostats, as it looked super promising for helping me achieve my goals. Is there a guide/readme file that explains how I can begin using Topostats on my computer with my own images (I have access to both a MacBook and a Windows computer, and can use whichever is the most compatible)? 

Thank you,
Ankush

**Reply by Jean-Du** [reply]
Hi, we have a guide on how to install TopoStats on windows:
[Importing gwy in PyCharm.pdf](https://github.com/AFM-SPM/TopoStats/files/6930173/Importing.gwy.in.PyCharm.pdf)

The file to start working with is pygwytracing.py, and we have a guide explaining how it works here:
[Guide on pygwytracing.pdf](https://github.com/AFM-SPM/TopoStats/files/6930242/Guide.on.pygwytracing.pdf)

If you haven't already, please do also check our publication, which gives a detailed explanation on what TopoStats does
https://www.sciencedirect.com/science/article/pii/S1046202321000207

**Comment by bobturneruk** [comment]
Try chaging https://github.com/AFM-SPM/TopoStats/blob/4ad2ab10264b48a7e80ee6431d823d983deff641/gwyconda.yml#L13 to `- wincertstore==0.2` in your downloaded `gwyconda.yml` (removing the version constraint). Please let me know if this helps :)

**Comment by bobturneruk** [comment]
Try getting rid of the `wincertstore` line altogether.

**Reply by bobturneruk** [reply]
Thanks for getting in touch again @aswinkl24 - I'm having a think!

**Reply by bobturneruk** [reply]
Can you please enter `python` at the command prompt you have there and paste the output?

**Comment by aswinkl24** [comment]


**Reply by bobturneruk** [reply]
32-bit Python 2 is definitely required. Is it available here? https://repo.anaconda.com/archive/Anaconda3-2021.05-Windows-x86.exe

**Reply by bobturneruk** [reply]
Will Anaconda3 allow a python 2 environment?

**Reply by bobturneruk** [reply]
Have you tried the new Docker install?

**Reply by bobturneruk** [reply]
Do let me know how you get on. Sorry I've not been more responsive on this thread.

**Comment by mary82104** [comment]
Hello everyone,

 thank you to all the members of the team who have worked on this software. I have installed the software TopoStats and tried to analyze the AFM imaging with help of it. The AFM imaging was converted from the ibw format into the spm format. The software has found the image but it has the problem with the analysis. My output was 0%. What should I do to analyze my imaging successfully? Thank you.

Best regard 
Maryna

**Reply by SylviaWhittle** [reply]
Hello @mary82104 !

Thank you for using our software, it means a lot to us. Could you share the output that is given when you try to run TopoStats by copying it and pasting it in a text file and uploading it here? It would greatly help in us assisting you 👍 (the entire output would be great - from when you typed the command to when it stops)

In the meantime, does the output stop once it says 0%? Usually when running TopoStats, I find that it can pause multiple times for a few seconds when processing images.

**Reply by mary82104** [reply]
Hello Sylvia.

Thank you for your answer. Ich have tried today once more this image to analyze with the help of the software. It was the result.




![test topostats](https://user-images.githubusercontent.com/118988927/204012269-67e6803b-786e-47e8-978c-7e121e3d9b81.png)

**Reply by SylviaWhittle** [reply]
@mary82104 

Thank you for sharing the log. It seems that the folder that TopoStats is looking in (`C:\Users\pharma`) does not have your .spm files inside it. Did you mean for the software to search `C:\Users\pharma` for your .spm files, or did you want it to search elsewhere? 

If you wanted it to search for .spm files there, then please could you check to see if that folder has your .spm files inside it? 

It seems like you might have wanted TopoStats to look inside `C:\test\Test\` for your .spm file. If this is the case then you can tell TopoStats to look there by editing a config file. 

Here is how to make a config file:

```
base_dir: ./tests/
output_dir: ./output
warnings: ignore
cores: 4
quiet: false
file_ext: .spm
loading:
  channel: Height
filter:
  run: true # Options : true, false
  threshold_method: std_dev # Options : std_dev (default), otsu, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.0
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  gaussian_size: 1.0121397464510862 # in px
  gaussian_mode: nearest
grains:
  run: true # Options : true, false
  # Thresholding by height
  threshold_method: std_dev # Options : std_dev, otsu, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.0
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  direction: upper # Options: upper, lower, both (defines whether to look for grains above or below thresholds or both)
  # Thresholding by area
  absolute_smallest_grain_size: 100
  absolute_area_threshold:
    upper: [ 400,600 ] # above surface [Low, High] in nm^2 (also takes null)
    lower: [ null, null ] # below surface [Low, High] in nm^2 (also takes null)
grainstats:
  run: true # Options : true, false
  cropped_size: 40.0 # Length (in nm) of square cropped images (can take -1 for grain-sized box)
  save_cropped_grains: true # Options : true, false
dnatracing:
  run: true # Options : true, false
plotting:
  run: true # Options : true, false
  save_format: png # Options : see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html
  image_set: all  # Options : all, core
  zrange: [null, null]  # low and high height range for core images (can take [null, null])
  colorbar: true  # Options : true, false
  axes: true # Options : true, false (due to off being a bool when parsed)
  cmap: nanoscope # Options : nanoscope, afmhot
  histogram_log_axis: false # Options : true, false
  ```

In order to  make a config file and tell TopoStats where to look for files, please copy this text, make a file called `my_config.yaml`, paste this text inside it. Then place the file in `C:\test\Test\` or wherever you would like to keep it. The first line of the file is where you tell TopoStats where to look for files. In your case, you might want to change it to: `base_dir: C:\Users\pharma\`. Save and close the file.

Then to run TopoStats using this configuration:

```
run_topostats --config "path_to_your_config_file"
```
where you should replace `path_to_your_config_file` with the path to where you saved your config file. (This is just to tell it where to look for the config file).

For example if you put `my_config.yaml` inside `C:\Users\pharma\` then run: `run_topostats --config "C:\Users\pharma\"`.

I hope this helps, but do say if it doesn't.
