### DISCUSSION TITLE
Issues with Channel

### DISCUSSION THREAD

**Discussion by ns-rse** [AFM-SPM/TopoStats#619] [General]
Splitting this out as its ultimately a different issue.

[Original Post](https://github.com/AFM-SPM/TopoStats/discussions/563#discussioncomment-6407606)

![image](https://github.com/AFM-SPM/TopoStats/assets/17566406/ac3dc0d5-0ba9-4d4c-85d6-76b597b24934)

@neumagen wrote

> What are the different channel names available to use? I tried ZSensor, zsensor, Height Sensor, PeakForceError, [ZSensor, PeakForceError], and ['ZSensor', 'PeakForceError']. What am I missing?

**Comment by ns-rse** [comment]
Hi @neumagen 

The error message here is saying that the requested channel `Height` is not present in the `.spm` channel, but that the found channels are `ZSensor` and `PeakForceError` (these are read from the file itself).

Its surprising that using either of these in your configuration didn't work.

Could you share the YAML file with `ZSensor` in and the output that it gives too please?

Ideally if you could copy and paste the file and output it makes it easier to search the text and find things, particularly for the YAML file. You can make it look like a code by putting it in a code block as shown below.

````
```
This is a code block.
```
````

Thanks @ns-rse

**Reply by ns-rse** [reply]
Thanks @ns-rse !

Here is the pasted YAML: 

```
# Config file generated 2023-07-11 12:10:15
# For more information on configuration and how to use it:
# https://afm-spm.github.io/TopoStats/main/configuration.html
base_dir: ./ # Directory in which to search for data files
output_dir: ./output # Directory to output results to
log_level: info # Verbosity of output. Options: warning, error, info, debug
cores: 2 # Number of CPU cores to utilise for processing multiple files simultaneously.
file_ext: .spm # File extension of the data files.
loading:
  channel: ZSensor # Channel to pull data from in the data files.
filter:
  run: true # Options : true, false
  row_alignment_quantile: 0.5 # below values may improve flattening of larger features
  threshold_method: std_dev # Options : otsu, std_dev, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    below: 10.0 # Threshold for data below the image background
    above: 1.0 # Threshold for data above the image background
  threshold_absolute:
    below: -1.0 # Threshold for data below the image background
    above: 1.0 # Threshold for data above the image background
  gaussian_size: 1.0121397464510862 # Gaussian blur intensity in px
  gaussian_mode: nearest
  # Scar remvoal parameters. Be careful with editing these as making the algorithm too sensitive may
  # result in ruining legitimate data.
  remove_scars:
    run: true
    removal_iterations: 2 # Number of times to run scar removal.
    threshold_low: 0.250 # below values make scar removal more sensitive
    threshold_high: 0.666 # below values make scar removal more sensitive
    max_scar_width: 4 # Maximum thichness of scars in pixels.
    min_scar_length: 16 # Minimum length of scars in pixels.
grains:
  run: true # Options : true, false
  # Thresholding by height
  threshold_method: std_dev # Options : std_dev, otsu, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    below: 10.0 # Threshold for grains below the image background
    above: 1.0 # Threshold for grains above the image background
  threshold_absolute:
    below: -1.0 # Threshold for grains below the image background
    above: 1.0 # Threshold for grains above the image background
  direction: above # Options: above, below, both (defines whether to look for grains above or below thresholds or both)
  # Thresholding by area
  smallest_grain_size_nm2: 50 # Size in nm^2 of tiny grains/blobs (noise) to remove, must be > 0.0
  absolute_area_threshold:
    above: [ 300, 3000 ] # above surface [Low, High] in nm^2 (also takes null)
    below: [ null, null ] # below surface [Low, High] in nm^2 (also takes null)
grainstats:
  run: true # Options : true, false
  edge_detection_method: binary_erosion # Options: canny, binary erosion. Do not change this unless you are sure of what this will do.
  cropped_size: 40.0 # Length (in nm) of square cropped images (can take -1 for grain-sized box)
dnatracing:
  run: true # Options : true, false
  min_skeleton_size: 10 # Minimum number of pixels in a skeleton for it to be retained.
  skeletonisation_method: topostats # Options : zhang | lee | thin | topostats
  pad_width: 1 # Cells to pad grains by when tracing
#  cores: 1 # Number of cores to use for parallel processing
plotting:
  run: true # Options : true, false
  save_format: png # Options : see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html
  pixel_interpolation: null # Options : https://matplotlib.org/stable/gallery/images_contours_and_fields/interpolation_methods.html
  image_set: core  # Options : all, core
  zrange: [null, null]  # low and high height range for core images (can take [null, null]). low <= high
  colorbar: true  # Options : true, false
  axes: true # Options : true, false (due to off being a bool when parsed)
  cmap: nanoscope # Options : nanoscope, afmhot, gwyddion
  mask_cmap: blu # Options : blu, jet_r and any in matplotlib
  histogram_log_axis: false # Options : true, false
  histogram_bins: 200 # Number of bins for histogram plots to use
  dpi: 100 # Dots Per Inch used in figures, if set to "figure" will use Matplotlib default
summary_stats:
  run: true # Whether to make summary plots for output data
  config: null
```


And here is the generated output:

```
(topostats) katie@Kaitlyns-MacBook-Air Monica % run_topostats --create-config-file my_config.yaml
[Tue, 11 Jul 2023 12:10:15] [INFO    ] [topostats] The YAML configuration file is valid.
[Tue, 11 Jul 2023 12:10:15] [INFO    ] [topostats] A sample configuration has been written to : /Users/katie/Desktop/Monica/my_config.yaml
[Tue, 11 Jul 2023 12:10:15] [INFO    ] [topostats] For more information on configuration and how to use it:
# https://afm-spm.github.io/TopoStats/main/configuration.html

(topostats) katie@Kaitlyns-MacBook-Air Monica % run_topostats
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] The YAML configuration file is valid.
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] The YAML plotting configuration file is valid.
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] Configuration run options are consistent, processing can proceed.
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] Configuration file loaded from      : None
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] Scanning for images in              : /Users/katie/Desktop/Monica
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] Output directory                    : output
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] Looking for images with extension   : .spm
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] Images with extension .spm in /Users/katie/Desktop/Monica : 1
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] Thresholding method (Filtering)     : std_dev
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] Thresholding method (Grains)        : std_dev
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] Extracting image from /Users/katie/Desktop/Monica/2023-03-30-3overhang.0_00000.spm
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] Loading image from : /Users/katie/Desktop/Monica/2023-03-30-3overhang.0_00000.spm
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] [2023-03-30-3overhang.0_00000] : Loaded image from : /Users/katie/Desktop/Monica/2023-03-30-3overhang.0_00000.spm
[Tue, 11 Jul 2023 12:11:06] [ERROR   ] [topostats] [2023-03-30-3overhang.0_00000] : Height not in .spm channel list: ['ZSensor', 'PeakForceError']
[Tue, 11 Jul 2023 12:11:06] [ERROR   ] [topostats] [io.py] [503] [2023-03-30-3overhang.0_00000] : Height not in .spm channel list: ['ZSensor', 'PeakForceError']
[Tue, 11 Jul 2023 12:11:06] [WARNING ] [topostats] [2023-03-30-3overhang.0_00000] Channel Height not found, skipping image.
Processing images from /Users/katie/Desktop/Monica, results are under output:   
[Tue, 11 Jul 2023 12:11:06] [INFO    ] [topostats] Saving image stats to : output/image_stats.csv.
Traceback (most recent call last):
  File "/Users/katie/anaconda3/envs/topostats/bin/run_topostats", line 8, in <module>
    sys.exit(legacy_run_topostats_entry_point())
  File "/Users/katie/anaconda3/envs/topostats/lib/python3.10/site-packages/topostats/entry_point.py", line 325, in legacy_run_topostats_entry_point
    run_topostats(args=args)
  File "/Users/katie/anaconda3/envs/topostats/lib/python3.10/site-packages/topostats/run_topostats.py", line 150, in run_topostats
    image_stats_all_df = pd.concat(image_stats_all.values())
  File "/Users/katie/anaconda3/envs/topostats/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 372, in concat
    op = _Concatenator(
  File "/Users/katie/anaconda3/envs/topostats/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 429, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```
