### ISSUE TITLE
Expand CITATION.cff

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#1021]
The `CITATION.cff` is missing details of earlier contributors to the package such as those listed in [TopoStats – A program for automated tracing of biomolecules from AFM images - ScienceDirect](https://www.sciencedirect.com/science/article/pii/S1046202321000207).

We should add these authors to the `CITATION.cff`, ideally ensuring we have their current contact details and metadata...

- `email`
- `affiliation`
- `orcid`

At the very least if people can't be contacted we should be able to find and add their [ORCiD](https://orcid.org).

**Comment by ns-rse** [comment]
Reading through the [paper](https://www.sciencedirect.com/science/article/pii/S1046202321000207) and the _CRediT authorship contribution statement_ section those noted to have contributed to the software for whom I don't have contact details are...

```
  - given-names: Joseph
    family-names: Beton
    email:
    affiliation:
    orcid:
  - given-names: Luzie
    family-names: Helfmann
    email:
    affiliation:
    orcid:
  - given-names: Robert
    family-names: Gray
    email:
    affiliation:
    orcid:
  - given-names: Agnel Praveen
    family-names: Joseph
    email:
    affiliation:
    orcid:
```
