### ISSUE TITLE
Add nbQA pre-commit hook and lint existing notebooks

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#1038]
Add [nbQA pre-commit hook](https://github.com/nbQA-dev/nbQA) to the `.pre-commit-config.yaml` to lint Notebooks.

## `.pre-commit-config.yaml`

The full set of available hooks is listed [here](https://github.com/nbQA-dev/nbQA/blob/master/.pre-commit-hooks.yaml)

```yaml
repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.1
  hooks:
   - id: nbqa-black
   - id: nbqa-check-ast
   - id: nbqa-flake8
   - id: nbqa-isort
   - id: nbqa-mypy
   - id: nbqa-pylint
   - id: nbqa-pyupgrade
```
