### ISSUE TITLE
[Bug]: "Curvature" image not generating per file in the processed folder

### ISSUE THREAD

**Issue by tcatley** [AFM-SPM/TopoStats#1054]
### Checklist

- [X] Find the offending file in the output. If processing halts, re-run analysis with `topostats --core 1 process`.
- [X] Describe the bug.
- [X] Include the configuration file.
- [ ] Copy of the output.
- [X] The exact command that failed. This is what you typed at the command line, including any options.
- [X] TopoStats version, this is reported by `topostats --version`
- [ ] Operating System and Python Version

### Describe the bug

When running an updated version of main (2.2.2.dev1282+gdf4cb02e7), the processed output only produces a single curvature image in the folder, rather than one for every .spm file processed. 

### Copy of the output

<img width="487" alt="Screenshot 2024-12-16 at 15 09 15" src="https://github.com/user-attachments/assets/eda4749c-83ca-4046-9bcb-8dff98bed87b" />

### Include the configuration file

```
# Configuration from TopoStats run completed : 2024-12-11 15:57:48
# For more information on configuration and how to use it:
# https://afm-spm.github.io/TopoStats/main/configuration.html
base_dir: /Volumes/shared/pyne_group/Shared/AFM_Data/Top2_HSF1/test
cores: 6
curvature:
  colourmap_normalisation_bounds: [-0.5, 0.5]
  run: true
disordered_tracing:
  mask_smoothing_params:
    dilation_iterations: 2
    gaussian_sigma: 2
    holearea_min_max: [0, null]
  min_skeleton_size: 10
  pad_width: 1
  pruning_params: {height_threshold: null, max_length: 10.0, method: topostats, method_outlier: mean_abs,
    method_values: mid}
  run: true
  skeletonisation_params: {height_bias: 0.5, method: topostats}
file_ext: .spm
filter:
  gaussian_mode: nearest
  gaussian_size: 1.0121397464510862
  otsu_threshold_multiplier: 1.0
  remove_scars: {max_scar_width: 4, min_scar_length: 16, removal_iterations: 2, run: false,
    threshold_high: 0.666, threshold_low: 0.25}
  row_alignment_quantile: 0.5
  run: true
  threshold_absolute: {above: 0.6, below: -1.0}
  threshold_method: std_dev
  threshold_std_dev: {above: 1.0, below: 10.0}
grains:
  absolute_area_threshold:
    above: [5000, 20000]
    below: [null, null]
  direction: above
  otsu_threshold_multiplier: 1.0
  remove_edge_intersecting_grains: true
  run: true
  smallest_grain_size_nm2: 50
  threshold_absolute: {above: 0.6, below: -1.0}
  threshold_method: absolute
  threshold_std_dev: {above: 1.0, below: 10.0}
  unet_config: {grain_crop_padding: 2, lower_norm_bound: -1.0, model_path: null, upper_norm_bound: 5.0}
  vetting: {class_connection_point_thresholds: null, class_conversion_size_thresholds: null,
    class_region_number_thresholds: null, class_size_thresholds: null, class_touching_threshold: 5,
    keep_largest_labelled_regions_classes: null, nearby_conversion_classes_to_convert: null}
grainstats: {cropped_size: -1, edge_detection_method: binary_erosion, extract_height_profile: true,
  run: true}
loading: {channel: Height}
log_level: info
nodestats: {branch_pairing_length: 20.0, node_extend_dist: 14.0, node_joining_length: 7.0,
  pad_width: 1, pair_odd_branches: false, run: true}
ordered_tracing: {ordering_method: nodestats, pad_width: 1, run: true}
output_dir: /Volumes/shared/pyne_group/Shared/AFM_Data/Top2_HSF1/test
plotting:
  axes: true
  cmap: null
  colorbar: true
  histogram_log_axis: false
  image_set: core
  mask_cmap: blue_purple_green
  num_ticks: [null, null]
  pixel_interpolation: null
  run: true
  savefig_dpi: 600
  savefig_format: null
  style: topostats.mplstyle
  zrange: [-3, 4]
splining: {method: rolling_window, rolling_window_size: 2e-08, run: true, spline_circular_smoothing: 5.0,
  spline_degree: 3, spline_linear_smoothing: 5.0, spline_step_size: 7e-09}
summary_stats: {config: null, run: false}
```

### TopoStats Version

Git main branch

### Python Version

3.12

### Operating System

MacOS M1/M2 (post-2021)
