### ISSUE TITLE
[Bug]: Bounding boxes for grain masks seem to be disrupting other masks and traces

### ISSUE THREAD

**Issue by tcatley** [AFM-SPM/TopoStats#1066]
### Checklist

- [X] Find the offending file in the output. If processing halts, re-run analysis with `topostats --core 1 process`.
- [X] Describe the bug.
- [X] Include the configuration file.
- [X] Copy of the log-file from running with `topostats --log-level debug <command>`.
- [X] The exact command that failed. This is what you typed at the command line, including any options.
- [X] TopoStats version, this is reported by `topostats --version`
- [X] Operating System and Python Version

### Describe the bug

I have an images with lots of overlapping molecules. The new bounding boxes which are drawn around the masks seem to be chopping up the masks on adjacent grains and effecting the subsequent traces. 
![20240802_GMP_RTdryup_KCl2 0_00014_above_masked](https://github.com/user-attachments/assets/f8627221-12aa-4af0-969e-4c6e36cd8553)
The centre bottom and the middle right of the mask image shows masks which have been cut off by the corner of a nearby mask. The spline and trace images show that this cutoff has also disrupted the traces. 
![20240802_GMP_RTdryup_KCl2 0_00014_above_disordered_trace](https://github.com/user-attachments/assets/df22848c-2af8-42a7-b9b2-a6e79dd72a4e)
![20240802_GMP_RTdryup_KCl2 0_00014_above_all_splines](https://github.com/user-attachments/assets/85b05d1d-135e-4311-914c-ccf5277b96b5)

### Copy of the log-file from running with `topostats --log-level debug <command>`

```
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [validation.py] [32] The YAML configuration file is valid.
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [validation.py] [32] The YAML plotting configuration file is valid.
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [processing.py] [1316] Configuration run options are consistent, processing can proceed.
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [run_modules.py] [139] Configuration file loaded from      : /Users/work/Documents/new_config.yaml
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [run_modules.py] [140] Scanning for images in              : /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [run_modules.py] [141] Output directory                    : /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [run_modules.py] [142] Looking for images with extension   : .spm
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [run_modules.py] [143] Images with extension .spm in /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure : 4
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [run_modules.py] [148] Thresholding method (Filtering)     : std_dev
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [run_modules.py] [149] Thresholding method (Grains)        : absolute
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [io.py] [748] Extracting image from /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/20240802_GMP_RTdryup_KCl2.0_00017.spm
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [io.py] [748] Extracting image from /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/20240802_GMP_RTdryup_KCl2.0_00014.spm
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [io.py] [748] Extracting image from /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/Extra images same sample/20240802_GMP_RTdryup_KCl2.0_00016.spm
[Fri, 03 Jan 2025 10:22:42] [INFO    ] [topostats] [io.py] [748] Extracting image from /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/Extra images same sample/20240802_GMP_RTdryup_KCl2.0_00021.spm
[Fri, 03 Jan 2025 10:23:09] [INFO    ] [topostats] [run_modules.py] [275] [20240802_GMP_RTdryup_KCl2.0_00017] Processing completed.
[Fri, 03 Jan 2025 10:23:20] [INFO    ] [topostats] [run_modules.py] [275] [20240802_GMP_RTdryup_KCl2.0_00021] Processing completed.
[Fri, 03 Jan 2025 10:23:23] [INFO    ] [topostats] [run_modules.py] [275] [20240802_GMP_RTdryup_KCl2.0_00014] Processing completed.
[Fri, 03 Jan 2025 10:23:30] [INFO    ] [topostats] [run_modules.py] [275] [20240802_GMP_RTdryup_KCl2.0_00016] Processing completed.
[Fri, 03 Jan 2025 10:23:30] [INFO    ] [topostats] [run_modules.py] [277] Saving image stats to : /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/image_stats.csv.
[Fri, 03 Jan 2025 10:23:30] [INFO    ] [topostats] [run_modules.py] [302] Saving all height profiles to /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/height_profiles.json
[Fri, 03 Jan 2025 10:23:30] [INFO    ] [topostats] [io.py] [397] No folder-wise statistics for directory nan, no grains detected in any images.
[Fri, 03 Jan 2025 10:23:30] [INFO    ] [topostats] [io.py] [397] No folder-wise statistics for directory nan, no grains detected in any images.
[Fri, 03 Jan 2025 10:23:30] [INFO    ] [topostats] [io.py] [395] Folder-wise statistics saved to: /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/folder_grain_stats.csv
[Fri, 03 Jan 2025 10:23:30] [INFO    ] [topostats] [io.py] [395] Folder-wise statistics saved to: /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/Extra images same sample/folder_grain_stats.csv
[Fri, 03 Jan 2025 10:23:30] [INFO    ] [topostats] [io.py] [395] Folder-wise statistics saved to: /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/folder_disordered_trace_stats.csv
[Fri, 03 Jan 2025 10:23:30] [INFO    ] [topostats] [io.py] [395] Folder-wise statistics saved to: /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/Extra images same sample/folder_disordered_trace_stats.csv
[Fri, 03 Jan 2025 10:23:31] [INFO    ] [topostats] [io.py] [395] Folder-wise statistics saved to: /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/folder_mol_stats.csv
[Fri, 03 Jan 2025 10:23:31] [INFO    ] [topostats] [io.py] [395] Folder-wise statistics saved to: /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/Extra images same sample/folder_mol_stats.csv
[Fri, 03 Jan 2025 10:23:31] [INFO    ] [topostats] [processing.py] [1389] 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ COMPLETE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  TopoStats Version           : 2.2.2.dev1320+gcf4682483
  Base Directory              : /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure
  File Extension              : .spm
  Files Found                 : 4
  Successfully Processed^1    : 4 (100.0%)
  All statistics              : /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/all_statistics.csv
  Distribution Plots          : Disabled. Enable in config 'summary_stats/run' if needed.

  Configuration               : /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis (sharred)/Figure_2_GQs_structure/config.yaml

  Email                       : topostats@sheffield.ac.uk
  Documentation               : https://afm-spm.github.io/topostats/
  Source Code                 : https://github.com/AFM-SPM/TopoStats/
  Bug Reports/Feature Request : https://github.com/AFM-SPM/TopoStats/issues/new/choose
  Citation File Format        : https://github.com/AFM-SPM/TopoStats/blob/main/CITATION.cff

  ^1 Successful processing of an image is detection of grains and calculation of at least
     grain statistics. If these have been disabled the percentage will be 0.

  If you encounter bugs/issues or have feature requests please report them at the above URL
  or email us.

  If you have found TopoStats useful please consider citing it. A Citation File Format is
  linked above and available from the Source Code page.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Include the configuration file

```
# Configuration from TopoStats run completed : 2025-01-03 10:33:44
# For more information on configuration and how to use it:
# https://afm-spm.github.io/TopoStats/main/configuration.html
base_dir: /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared
  drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis
  (sharred)/Figure_2_GQs_structure
cores: 6
curvature:
  colourmap_normalisation_bounds: [-0.5, 0.5]
  run: true
disordered_tracing:
  mask_smoothing_params:
    dilation_iterations: 2
    gaussian_sigma: 2
    holearea_min_max: [0, null]
  min_skeleton_size: 10
  pad_width: 1
  pruning_params: {height_threshold: null, max_length: 10.0, method: topostats, method_outlier: mean_abs,
    method_values: mid}
  run: true
  skeletonisation_params: {height_bias: 0.5, method: topostats}
file_ext: .spm
filter:
  gaussian_mode: nearest
  gaussian_size: 1.0121397464510862
  otsu_threshold_multiplier: 1.0
  remove_scars: {max_scar_width: 4, min_scar_length: 16, removal_iterations: 2, run: false,
    threshold_high: 0.666, threshold_low: 0.25}
  row_alignment_quantile: 0.5
  run: true
  threshold_absolute: {above: 0.6, below: -1.0}
  threshold_method: std_dev
  threshold_std_dev: {above: 1.0, below: 10.0}
grains:
  absolute_area_threshold:
    above: [100, 30000]
    below: [null, null]
  direction: above
  otsu_threshold_multiplier: 1.0
  remove_edge_intersecting_grains: false
  run: true
  smallest_grain_size_nm2: 50
  threshold_absolute: {above: 0.5, below: -1.0}
  threshold_method: absolute
  threshold_std_dev: {above: 1.0, below: 10.0}
  unet_config: {grain_crop_padding: 2, lower_norm_bound: -1.0, model_path: null, upper_norm_bound: 5.0}
  vetting: {class_connection_point_thresholds: null, class_conversion_size_thresholds: null,
    class_region_number_thresholds: null, class_size_thresholds: null, class_touching_threshold: 5,
    keep_largest_labelled_regions_classes: null, nearby_conversion_classes_to_convert: null}
grainstats: {cropped_size: -1, edge_detection_method: binary_erosion, extract_height_profile: true,
  run: true}
loading: {channel: Height}
log_level: info
nodestats: {branch_pairing_length: 20.0, node_extend_dist: 14.0, node_joining_length: 7.0,
  pad_width: 1, pair_odd_branches: false, run: true}
ordered_tracing: {ordering_method: nodestats, pad_width: 1, run: true}
output_dir: /Users/work/Library/CloudStorage/GoogleDrive-t.catley@sheffield.ac.uk/Shared
  drives/Pyne_group_data/Papers/Simon Quadruplex manuscript/TopoStats data analysis
  (sharred)/Figure_2_GQs_structure
plotting:
  axes: true
  cmap: null
  colorbar: true
  histogram_log_axis: false
  image_set: all
  mask_cmap: blue_purple_green
  num_ticks: [null, null]
  pixel_interpolation: null
  run: true
  savefig_dpi: 600
  savefig_format: null
  style: topostats.mplstyle
  zrange: [-3, 4]
splining: {method: rolling_window, rolling_window_size: 2e-08, run: true, spline_circular_smoothing: 5.0,
  spline_degree: 3, spline_linear_smoothing: 5.0, spline_step_size: 7e-09}
summary_stats: {config: null, run: false}
```

### To Reproduce

I can provide the file on request - it is for an external collaborator paper so don't want to post here. 

### TopoStats Version

Git main branch

### Python Version

3.11

### Operating System

MacOS M1/M2 (post-2021)
