### ISSUE TITLE
Rationalise config.yaml and parametrise plotting dictionary

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#255]
**Is your feature request related to a problem? Please describe.**

On the back of #241 it has been [suggested](https://github.com/AFM-SPM/TopoStats/issues/241#issuecomment-1205012401) to structure the configuration file as below so that each stage of processing has its own set of options that define whether it is run or not.

```yaml
base_dir: ./tests/
output_dir: ./output
save_plots: true
warnings: ignore
cores: 4
quiet: false
file_ext: .spm
channel: Height
amplify_level: 1.0
filter:
  run: true # Options : true, false
  threshold:
    method: std_dev # Options : otsu, std_dev, absolute
    otsu_multiplier: 1.0
    std_dev: 1.0
    absolute:
      - 1
      - -1
grains:
  run: true # Options : true, false
  gaussian_size: 2.0 
  gaussian_mode: nearest
  absolute_smallest_grain_size: 100
  background: 0.0
  mask_direction: upper # Options: upper, lower (currently only applied to thresh+mask image)
  save_cropped_grains: True
  threshold:
    method: std_dev # Options : otsu, std_dev, absolute
    otsu_multiplier: 1.0
    std_dev: 1.0
    absolute:
      - 1
      - -1
dnatracing:
  run: true # Options : true, false
plotting:
  run: true # Options : true, false
  save: True
  zrange: [0, 3] # low and high height range for core images (can take [null, null])
  image_set: core # Options : all, core
  colorbar: True
  cmap: nanoscope # Options : nanoscope, afmhot
```

This in turn has knock on effects on how options are passed into `process_scan()` and the following would help keep things simpler...

```python
def process_scan(
    image_path: Union[str, Path],
    base_dir: Union[str, Path],
    filter_config: dict,
    grains_config: dict,
    dnatracing_config: dict,
    plotting_config: dict,
    channel: str = "Height",
    amplify_level: float = 1.0,
    output_dir: Union[str, Path] = "output",
) -> None:
    ...
# Filter Image :
    #
    # The Filters class has a convenience method that runs the instantiated class in full.
    if filter_config["run"]:
        filtered_image = Filters(
            image_path,
            threshold_method=filter_config["threshold"]["method"],
            otsu_threshold_multiplier=filter_config["threshold"]["otsu_multiplier"],
            threshold_std_dev=filter_config["threshold"]["std_dev"],
            threshold_absolute_lower=filter_config["threshold"]["absolute"][0],
            threshold_absolute_upper=filter_config["threshold"]["absolute"][1],
            channel=channel,
            amplify_level=amplify_level,
            output_dir=filter_out_path,
        )
        filtered_image.filter_image()
    # Find Grains :
    # The Grains class also has a convenience method that runs the instantiated class in full.
    if grains_config["run"]:
        try:
            LOGGER.info(f"[{filtered_image.filename}] : *** Grain Finding ***")
            ...
```

```python
    processing_function = partial(
        process_scan,
        base_dir=config["base_dir"],
        channel=config["channel"],
        amplify_level=config["amplify_level"],
        filter_config=config["filter"],
        grains_config=config["grains"],
        dnatracing_config=config["dnatracing"],
        plotting_config=config["plotting"],
        output_dir=config["output_dir"]
    )
```

**IMPORTANT** - If we are sensible and align the class/method options with the configuration names then we will be able to leverage `**kwargs` when passing a dictionary of configuration options into an argument (for more information see [Python args and kwargs: Demystified – Real Python](https://realpython.com/python-kwargs-and-args/)).

Further the `PLOT_DICT` defined in `run_topostats.yaml` should be paramterised to its own YAML file that is loaded by default (but can be specified by user).
