### ISSUE TITLE
Add a Citation File Format file to the repository

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#380]
The [Citation File Format (CFF)](https://github.com/citation-file-format/citation-file-format/) is a citation metadata format for software and datasets.

TopoStats would benefit from including a CFF file.

Sample might be

```yaml
cff-version: 1.2.0
message: If you use this software, please cite it using these metadata.
title: TopoStats
abstract: TopoStats is software for processing and analysing Atomic Force Microscopy images.
authors:
  - family-names: Pyne
    given-names: Alice
    orcid: "https://orcid.org/0000-0002-2658-8987"
  - family-names: Whittle
    given-names: Sylvia
    orcid: ""
  - family-names: Gamill
    given-names: Max
    orcid: ""
  - family-names: Shephard 
    given-names: Neil
    orcid: "https://orcid.org/0000-0001-8301-6857"
  - family-names: Du
    given-names: Mingxue
    orcid: ""
  - family-names: Thomas
    given-names: Ben
    orcid: "https://orcid.org/0000-0002-3986-213X"
  - family-names: Rollins
    given-names: Eddie
    orcid: ""
  - family-names: Beton
    given-names: Joe
    orcid: ""
  - family-names: Turner
    given-names: Robert
    orcid: "https://orcid.org/0000-0002-1353-1404"
  - name: "The TopoStats Team"
version: 2.0.0
date-released: "2022-11-22"
license: 
  - GPLv3
  - LGPL
repository-code: "https://github.com/AFM-SPM/TopoStats/"
```
