### ISSUE TITLE
Dnatracing division by zero

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#402]
**Describe the bug**
When processing the following file, TopoStats throws a division by zero error during `dnatracing`. 

**To Reproduce**

Run topostats on the following file and with the following config:

File: https://drive.google.com/drive/folders/1mFtdYHl6g0kxxBpJcpY9a65t1TP-kqyU

Config:

```
base_dir: ./raphael/20220819/C3
output_dir: ./output/20220819/C3
warnings: ignore
cores: 4
quiet: false
file_ext: .spm
loading:
  channel: Height
filter:
  run: true # Options : true, false
  threshold_method: std_dev # Options : otsu, std_dev, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.0
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  gaussian_size: 1.0121397464510862 # in px
  gaussian_mode: nearest
grains:
  run: true # Options : true, false
  # Thresholding by height
  threshold_method: std_dev # Options : std_dev, otsu, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.0
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  direction: upper # Options: upper, lower, both (defines whether to look for grains above or below thresholds or both)
  # Thresholding by area
  absolute_smallest_grain_size: 100
  absolute_area_threshold:
    upper: [ 300, 100000 ] # above surface [Low, High] in nm^2 (also takes null)
    lower: [ null, null ] # below surface [Low, High] in nm^2 (also takes null)
grainstats:
  run: true # Options : true, false
  cropped_size: 40.0 # Length (in nm) of square cropped images (can take -1 for grain-sized box)
  save_cropped_grains: true # Options : true, false
dnatracing:
  run: true # Options : true, false
plotting:
  run: true # Options : true, false
  save_format: png # Options : see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html
  image_set: all  # Options : all, core
  zrange: [-4, 4]  # low and high height range for core images (can take [null, null])
  colorbar: true  # Options : true, false
  axes: true # Options : true, false (due to off being a bool when parsed)
  cmap: nanoscope # Options : nanoscope, afmhot
  histogram_log_axis: false # Options : true, false
```

**Output**

```
❯ run_topostats --config ./my_config.yaml
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] Configuration is valid.
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] Plotting configuration is valid.
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] Configuration file loaded from      : ./my_config.yaml
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] Scanning for images in              : raphael/20220819/C3
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] Output directory                    : output/20220819/C3
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] Looking for images with extension   : .spm
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] Images with extension .spm in raphael/20220819/C3 : 1
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] Thresholding method (Filtering)     : std_dev
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] Thresholding method (Grains)        : std_dev
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] Extracting image from raphael/20220819/C3/C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes.0_00013.spm
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] Loading image from : raphael/20220819/C3/C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes.0_00013.spm
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes.0_00013] : Loaded image from : raphael/20220819/C3/C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes.0_00013.spm
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes.0_00013] : Extracted channel Height
[Tue, 13 Dec 2022 18:50:16] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes.0_00013] : Pixel to nm scaling : 7.8125
Processing images from raphael/20220819/C3, results are under output/20220819/C3:   0%|               | 0/1 [00:00<?, ?it/s][Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] image_path: raphael/20220819/C3/C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes.0_00013
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] image_path: raphael/20220819/C3/C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] Processing : C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] NO SUFFIX : 
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] output_dir: output/20220819/C3
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] _output_dir: output/20220819/C3/Processed
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] processed path: output/20220819/C3/Processed
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] folder path: raphael/20220819/C3
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats]  filter out path: output/20220819/C3/Processed/C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013/filters
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats]  grains out path: output/20220819/C3/Processed/C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013/grains
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Median flattening without mask
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Plane tilt removal without mask
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] x-polyfit 1st order: [  0.27207554 -17.41082201]
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] y-polyfit 1st order: [-1.43326723e-18  5.07346103e-16]
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] removing x plane tilt
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] removing y plane tilt
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Remove quadratic bow without mask
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] x polyfit 2nd order: [-8.73271071e-05  1.10905426e-02 -1.76437234e+01]
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Masking (upper) Threshold: -16.75327140083654
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Masking (lower) Threshold: -21.95389593854906
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Median flattening with mask
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Plane tilt removal with mask
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] x-polyfit 1st order: [ 4.20504532e-06 -1.08544093e-02]
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] y-polyfit 1st order: [-1.60607249e-18  1.29741179e-16]
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] removing x plane tilt
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] removing y plane tilt
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Remove quadratic bow with mask
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] x polyfit 2nd order: [-8.14653855e-05  1.03461040e-02 -2.28122592e-01]
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Zero averaging background : 0.1146772811694596 nm
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Applying Gaussian filter (mode : nearest; Gaussian blur (px) : 1.0121397464510862).
[Tue, 13 Dec 2022 18:50:17] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Plotting Filtering Images
[Tue, 13 Dec 2022 18:50:20] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Image saved to : output/20220819/C3/Processed/C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013_processed
[Tue, 13 Dec 2022 18:50:20] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : *** Grain Finding ***
[Tue, 13 Dec 2022 18:50:20] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Thresholding method (grains) : std_dev
[Tue, 13 Dec 2022 18:50:20] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Processing upper threshold (0.34804475650010547)
[Tue, 13 Dec 2022 18:50:20] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Masking (upper) Threshold: 0.34804475650010547
[Tue, 13 Dec 2022 18:50:20] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Labelling Regions
[Tue, 13 Dec 2022 18:50:20] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Tidying borders
[Tue, 13 Dec 2022 18:50:20] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Labelling Regions
[Tue, 13 Dec 2022 18:50:20] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Region properties calculated (upper)
[Tue, 13 Dec 2022 18:50:20] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Coloured regions
[Tue, 13 Dec 2022 18:50:20] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Extracted bounding boxes (upper)
[Tue, 13 Dec 2022 18:50:20] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Plotting Grain Finding Images
[Tue, 13 Dec 2022 18:50:21] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013_upper] : Image saved to : output/20220819/C3/Processed/C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013_upper_processed_masked
[Tue, 13 Dec 2022 18:50:21] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : *** Grain Statistics ***
[Tue, 13 Dec 2022 18:50:21] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Processing grain: 0
[Tue, 13 Dec 2022 18:50:21] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Processing grain: 1
[Tue, 13 Dec 2022 18:50:21] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Processing grain: 2
[Tue, 13 Dec 2022 18:50:22] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Processing grain: 3
[Tue, 13 Dec 2022 18:50:22] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Processing grain: 4
[Tue, 13 Dec 2022 18:50:22] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : *** DNA Tracing ***
[Tue, 13 Dec 2022 18:50:22] [INFO    ] [topostats] [C3_1ng_Imob_in_MgCl2_3x_NiCl2_washes_0_00013] : Gaussian filter applied.
Processing images from raphael/20220819/C3, results are under output/20220819/C3:   0%|               | 0/1 [00:06<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/sylvi/opt/anaconda3/envs/scars/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/run_topostats.py", line 352, in process_scan
    dna_traces[direction].trace_dna()
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/tracing/dnatracing.py", line 91, in trace_dna
    self.get_splined_traces()
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/tracing/dnatracing.py", line 426, in get_splined_traces
    while nbr / step_size < 4:
ZeroDivisionError: division by zero
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sylvi/opt/anaconda3/envs/scars/bin/run_topostats", line 8, in <module>
    sys.exit(main())
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/run_topostats.py", line 459, in main
    for img, result in pool.imap_unordered(
  File "/Users/sylvi/opt/anaconda3/envs/scars/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
ZeroDivisionError: division by zero
```

**(Not required if using Docker) Your computer configuration (please complete the following information):**
 - OS: MacOS
 - topostats version: 2.0.0
 - Python version: 3.10
