### ISSUE TITLE
Grainstats crash

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#404]
**Describe the bug**
A crash occurs while processing an AFM image which appears to originate from `grainstats.py`. The error is `ValueError: operands could not be broadcast together with shapes (0,) (2,) ` which is an issue with handling arrays. Check grainstats code to ensure that there are measures to check for bad array size combinations and also diagnose how they can arise. 

**To Reproduce**

Run TopoStats on the following file: https://drive.google.com/drive/folders/1_EUP6WyfsU5uSTO0eUXh1JUkxdsXDEab

Using the following config:

```yaml
base_dir: ./raphael/20220819/E4
output_dir: ./output/20220819/E4
warnings: ignore
cores: 4
quiet: false
file_ext: .spm
loading:
  channel: Height
filter:
  run: true # Options : true, false
  threshold_method: std_dev # Options : otsu, std_dev, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.0
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  gaussian_size: 1.0121397464510862 # in px
  gaussian_mode: nearest
grains:
  run: true # Options : true, false
  # Thresholding by height
  threshold_method: std_dev # Options : std_dev, otsu, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.0
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  direction: upper # Options: upper, lower, both (defines whether to look for grains above or below thresholds or both)
  # Thresholding by area
  absolute_smallest_grain_size: 100
  absolute_area_threshold:
    upper: [ 300, 100000 ] # above surface [Low, High] in nm^2 (also takes null)
    lower: [ null, null ] # below surface [Low, High] in nm^2 (also takes null)
grainstats:
  run: true # Options : true, false
  cropped_size: 40.0 # Length (in nm) of square cropped images (can take -1 for grain-sized box)
  save_cropped_grains: true # Options : true, false
dnatracing:
  run: true # Options : true, false
plotting:
  run: true # Options : true, false
  save_format: png # Options : see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html
  image_set: all  # Options : all, core
  zrange: [-4, 4]  # low and high height range for core images (can take [null, null])
  colorbar: true  # Options : true, false
  axes: true # Options : true, false (due to off being a bool when parsed)
  cmap: nanoscope # Options : nanoscope, afmhot
  histogram_log_axis: false # Options : true, false

```

**Expected behavior**

**Output**

```bash
❯ run_topostats --config ./my_config.yaml
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] Configuration is valid.
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] Plotting configuration is valid.
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] Configuration file loaded from      : ./my_config.yaml
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] Scanning for images in              : raphael/20220819/E4
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] Output directory                    : output/20220819/E4
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] Looking for images with extension   : .spm
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] Images with extension .spm in raphael/20220819/E4 : 1
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] Thresholding method (Filtering)     : std_dev
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] Thresholding method (Grains)        : std_dev
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] Extracting image from raphael/20220819/E4/E4-24h-nm.0_00006.spm
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] Loading image from : raphael/20220819/E4/E4-24h-nm.0_00006.spm
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] [E4-24h-nm.0_00006] : Loaded image from : raphael/20220819/E4/E4-24h-nm.0_00006.spm
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] [E4-24h-nm.0_00006] : Extracted channel Height
[Wed, 14 Dec 2022 16:04:40] [INFO    ] [topostats] [E4-24h-nm.0_00006] : Pixel to nm scaling : 7.8125
Processing images from raphael/20220819/E4, results are under output/20220819/E4:   0%|       | 0/1 [00:00<?, ?it/s][Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] image_path: raphael/20220819/E4/E4-24h-nm.0_00006
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] image_path: raphael/20220819/E4/E4-24h-nm_0_00006
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] Processing : E4-24h-nm_0_00006
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] NO SUFFIX : 
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] output_dir: output/20220819/E4
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] _output_dir: output/20220819/E4/Processed
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] processed path: output/20220819/E4/Processed
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] folder path: raphael/20220819/E4
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats]  filter out path: output/20220819/E4/Processed/E4-24h-nm_0_00006/filters
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats]  grains out path: output/20220819/E4/Processed/E4-24h-nm_0_00006/grains
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Median flattening without mask
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Plane tilt removal without mask
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] x-polyfit 1st order: [-0.04713146  6.01015864]
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] y-polyfit 1st order: [ 1.15473115e-18 -1.93442339e-16]
[Wed, 14 Dec 2022 16:04:41] [INFO    ] [topostats] removing x plane tilt
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] removing y plane tilt
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Remove quadratic bow without mask
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] x polyfit 2nd order: [ 6.36937838e-06 -1.62419149e-03  6.07891608e+00]
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Masking (upper) Threshold: 6.356437682870245
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Masking (lower) Threshold: 2.5687851369480454
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Median flattening with mask
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Plane tilt removal with mask
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] x-polyfit 1st order: [ 2.53338788e-05 -3.03124756e-03]
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] y-polyfit 1st order: [ 2.41249252e-19 -6.02495788e-17]
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] removing x plane tilt
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] removing y plane tilt
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Remove quadratic bow with mask
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] x polyfit 2nd order: [ 6.19843233e-06 -1.58060024e-03  6.38808294e-02]
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Zero averaging background : -0.033168189250849044 nm
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Applying Gaussian filter (mode : nearest; Gaussian blur (px) : 1.0121397464510862).
[Wed, 14 Dec 2022 16:04:42] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Plotting Filtering Images
[Wed, 14 Dec 2022 16:04:46] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Image saved to : output/20220819/E4/Processed/E4-24h-nm_0_00006_processed
[Wed, 14 Dec 2022 16:04:46] [INFO    ] [topostats] [E4-24h-nm_0_00006] : *** Grain Finding ***
[Wed, 14 Dec 2022 16:04:46] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Thresholding method (grains) : std_dev
[Wed, 14 Dec 2022 16:04:46] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing upper threshold (0.2577153403696904)
[Wed, 14 Dec 2022 16:04:46] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Masking (upper) Threshold: 0.2577153403696904
[Wed, 14 Dec 2022 16:04:46] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Labelling Regions
[Wed, 14 Dec 2022 16:04:46] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Tidying borders
[Wed, 14 Dec 2022 16:04:46] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Labelling Regions
[Wed, 14 Dec 2022 16:04:46] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Region properties calculated (upper)
[Wed, 14 Dec 2022 16:04:46] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Coloured regions
[Wed, 14 Dec 2022 16:04:46] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Extracted bounding boxes (upper)
[Wed, 14 Dec 2022 16:04:46] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Plotting Grain Finding Images
[Wed, 14 Dec 2022 16:04:47] [INFO    ] [topostats] [E4-24h-nm_0_00006_upper] : Image saved to : output/20220819/E4/Processed/E4-24h-nm_0_00006_upper_processed_masked
[Wed, 14 Dec 2022 16:04:47] [INFO    ] [topostats] [E4-24h-nm_0_00006] : *** Grain Statistics ***
[Wed, 14 Dec 2022 16:04:47] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 0
[Wed, 14 Dec 2022 16:04:47] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 1
[Wed, 14 Dec 2022 16:04:47] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 2
[Wed, 14 Dec 2022 16:04:48] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 3
[Wed, 14 Dec 2022 16:04:48] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 4
[Wed, 14 Dec 2022 16:04:48] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 5
[Wed, 14 Dec 2022 16:04:49] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 6
[Wed, 14 Dec 2022 16:04:49] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 7
[Wed, 14 Dec 2022 16:04:49] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 8
[Wed, 14 Dec 2022 16:04:49] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 9
[Wed, 14 Dec 2022 16:04:50] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 10
[Wed, 14 Dec 2022 16:04:50] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 11
[Wed, 14 Dec 2022 16:04:50] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 12
[Wed, 14 Dec 2022 16:04:50] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 13
[Wed, 14 Dec 2022 16:04:51] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 14
[Wed, 14 Dec 2022 16:04:51] [INFO    ] [topostats] [E4-24h-nm_0_00006] : Processing grain: 15
Processing images from raphael/20220819/E4, results are under output/20220819/E4:   0%|       | 0/1 [00:11<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/sylvi/opt/anaconda3/envs/scars/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/run_topostats.py", line 329, in process_scan
    ).calculate_stats()
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/grainstats.py", line 218, in calculate_stats
    radius_stats = self.calculate_radius_stats(edges, points)
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/grainstats.py", line 368, in calculate_radius_stats
    displacements = self._calculate_displacement(edges, centroid)
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/grainstats.py", line 400, in _calculate_displacement
    return np.array(edges) - centroid
ValueError: operands could not be broadcast together with shapes (0,) (2,) 
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sylvi/opt/anaconda3/envs/scars/bin/run_topostats", line 8, in <module>
    sys.exit(main())
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/run_topostats.py", line 459, in main
    for img, result in pool.imap_unordered(
  File "/Users/sylvi/opt/anaconda3/envs/scars/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
ValueError: operands could not be broadcast together with shapes (0,) (2,) 
```

**(Not required if using Docker) Your computer configuration (please complete the following information):**
 - OS: MacOS
 - topostats version: 2.0.0
 - Python version: 3.10
