### ISSUE TITLE
Histogram plotting crash

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#410]
**Describe the bug**
When processing some spm files, the histogram plot crashes. This appears to be due to an internal call to `np.linspace` having some limit exceeded.

**To Reproduce**

Run TopoStats on the following spm file: https://drive.google.com/drive/folders/1wFauyUQKOmxBQ1JqudPJseTqJUK8Vnal

Using the following config:

```
base_dir: ./raphael/20220825/A3
output_dir: ./output/20220825/A3
warnings: ignore
cores: 6
quiet: false
file_ext: .spm
loading:
  channel: Height
filter:
  run: true # Options : true, false
  threshold_method: std_dev # Options : otsu, std_dev, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.0
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  gaussian_size: 1.0121397464510862 # in px
  gaussian_mode: nearest
grains:
  run: true # Options : true, false
  # Thresholding by height
  threshold_method: std_dev # Options : std_dev, otsu, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.5
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  direction: upper # Options: upper, lower, both (defines whether to look for grains above or below thresholds or both)
  # Thresholding by area
  absolute_smallest_grain_size: 300
  absolute_area_threshold:
    upper: [ 4000, 100000 ] # above surface [Low, High] in nm^2 (also takes null)
    lower: [ null, null ] # below surface [Low, High] in nm^2 (also takes null)
grainstats:
  run: true # Options : true, false
  cropped_size: 40.0 # Length (in nm) of square cropped images (can take -1 for grain-sized box)
  save_cropped_grains: true # Options : true, false
dnatracing:
  run: true # Options : true, false
plotting:
  run: true # Options : true, false
  save_format: png # Options : see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html
  image_set: all  # Options : all, core
  zrange: [-4, 4]  # low and high height range for core images (can take [null, null])
  colorbar: true  # Options : true, false
  axes: true # Options : true, false (due to off being a bool when parsed)
  cmap: nanoscope # Options : nanoscope, afmhot
  histogram_log_axis: false # Options : true, false
```

**Output**

```
❯ run_topostats --config my_config.yaml
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] Configuration is valid.
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] Plotting configuration is valid.
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] Configuration file loaded from      : my_config.yaml
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] Scanning for images in              : raphael/20220825/A3
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] Output directory                    : output/20220825/A3
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] Looking for images with extension   : .spm
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] Images with extension .spm in raphael/20220825/A3 : 1
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] Thresholding method (Filtering)     : std_dev
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] Thresholding method (Grains)        : std_dev
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] Extracting image from raphael/20220825/A3/A3_MgCl2_immobilization_3x_NiCl2_washes.0_00012.spm
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] Loading image from : raphael/20220825/A3/A3_MgCl2_immobilization_3x_NiCl2_washes.0_00012.spm
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes.0_00012] : Loaded image from : raphael/20220825/A3/A3_MgCl2_immobilization_3x_NiCl2_washes.0_00012.spm
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes.0_00012] : Extracted channel Height
[Mon, 19 Dec 2022 10:56:29] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes.0_00012] : Pixel to nm scaling : 2.9296875
Processing images from raphael/20220825/A3, results are under output/20220825/A3:   0%|                                                                       | 0/1 [00:00<?, ?it/s]dyld[22395]: Assertion failed: (!leaf()), function children, file BTree.h, line 153.

[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] image_path: raphael/20220825/A3/A3_MgCl2_immobilization_3x_NiCl2_washes.0_00012
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] image_path: raphael/20220825/A3/A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] Processing : A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] NO SUFFIX : 
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] output_dir: output/20220825/A3
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] _output_dir: output/20220825/A3/Processed
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] processed path: output/20220825/A3/Processed
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] folder path: raphael/20220825/A3
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats]  filter out path: output/20220825/A3/Processed/A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012/filters
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats]  grains out path: output/20220825/A3/Processed/A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012/grains
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012] : Median flattening without mask
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012] : Plane tilt removal without mask
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] x-polyfit 1st order: [0. 0.]
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] y-polyfit 1st order: [ 4.70897828e-20 -1.62801683e-17]
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] x gradient is zero, skipping plane tilt x removal
[Mon, 19 Dec 2022 10:56:30] [INFO    ] [topostats] removing y plane tilt
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012] : Remove quadratic bow without mask
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] x polyfit 2nd order: [ 3.22235901e-25 -2.68759477e-20 -1.37445795e-18]
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012] : Masking (upper) Threshold: 14.646051781817809
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012] : Masking (lower) Threshold: -144.95257674062898
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012] : Median flattening with mask
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012] : Plane tilt removal with mask
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] x-polyfit 1st order: [0. 0.]
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] y-polyfit 1st order: [0. 0.]
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] x gradient is zero, skipping plane tilt x removal
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] y gradient is zero, skipping plane tilt y removal
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012] : Remove quadratic bow with mask
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] x polyfit 2nd order: [0. 0. 0.]
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] quadratic polyfit returns zero, skipping quadratic removal
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012] : Zero averaging background : 0.023439585792428094 nm
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012] : Applying Gaussian filter (mode : nearest; Gaussian blur (px) : 1.0121397464510862).
[Mon, 19 Dec 2022 10:56:31] [INFO    ] [topostats] [A3_MgCl2_immobilization_3x_NiCl2_washes_0_00012] : Plotting Filtering Images
Processing images from raphael/20220825/A3, results are under output/20220825/A3:   0%|                                                                       | 0/1 [00:05<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/sylvi/opt/anaconda3/envs/scars/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/run_topostats.py", line 240, in process_scan
    Images(array, **plotting_config["plot_dict"][plot_name]).plot_histogram_and_save()
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/plottingfuncs.py", line 117, in plot_histogram_and_save
    ax.hist(self.data.flatten().astype(float), bins="auto", log=self.histogram_log_axis)
  File "/Users/sylvi/opt/anaconda3/envs/scars/lib/python3.10/site-packages/matplotlib/__init__.py", line 1423, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/sylvi/opt/anaconda3/envs/scars/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 6737, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "<__array_function__ internals>", line 180, in histogram
  File "/Users/sylvi/opt/anaconda3/envs/scars/lib/python3.10/site-packages/numpy/lib/histograms.py", line 793, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/Users/sylvi/opt/anaconda3/envs/scars/lib/python3.10/site-packages/numpy/lib/histograms.py", line 446, in _get_bin_edges
    bin_edges = np.linspace(
  File "<__array_function__ internals>", line 180, in linspace
  File "/Users/sylvi/opt/anaconda3/envs/scars/lib/python3.10/site-packages/numpy/core/function_base.py", line 135, in linspace
    y = _nx.arange(0, num, dtype=dt).reshape((-1,) + (1,) * ndim(delta))
ValueError: Maximum allowed size exceeded
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sylvi/opt/anaconda3/envs/scars/bin/run_topostats", line 8, in <module>
    sys.exit(main())
  File "/Users/sylvi/Documents/GitKraken/TopoStats/topostats/run_topostats.py", line 459, in main
    for img, result in pool.imap_unordered(
  File "/Users/sylvi/opt/anaconda3/envs/scars/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
ValueError: Maximum allowed size exceeded
```

**(Not required if using Docker) Your computer configuration (please complete the following information):**
 - OS: MacOS
 - topostats version: 2.0.0
 - Python version: 3.10
