### ISSUE TITLE
FileExistsError caused by file names containing periods

### ISSUE THREAD

**Issue by Jean-Du** [AFM-SPM/TopoStats#430]
**Describe the bug**
When running multiple files with periods in their names, the part after the period is discarded when creating directories named after the files, so if the part before the period is identical, the following error is triggered: 
`FileExistsError: [Errno 17] Cannot create a file when that file already exists: 'Processed\\[name of the file before the period]\\grains\\lower'`

**To Reproduce**

- Command used to run topostats
```
run_topostats --config config.yaml
```

- Config file (you can attach this or paste it below)
```yaml
base_dir: ./
output_dir: ./output
warnings: ignore
cores: 4
quiet: false
file_ext: .spm
loading:
  channel: Height
filter:
  run: true # Options : true, false
  threshold_method: std_dev # Options : std_dev (default), otsu, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.0
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  gaussian_size: 1.0121397464510862 # in px
  gaussian_mode: nearest
grains:
  run: true # Options : true, false
  # Thresholding by height
  threshold_method: std_dev # Options : std_dev, otsu, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 1.0
    upper: 1.0
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  direction: upper # Options: upper, lower, both (defines whether to look for grains above or below thresholds or both)
  # Thresholding by area
  absolute_smallest_grain_size: 100
  absolute_area_threshold:
    upper: [ 300,800 ] # above surface [Low, High] in nm^2 (also takes null)
    lower: [ null, null ] # below surface [Low, High] in nm^2 (also takes null)
grainstats:
  run: true # Options : true, false
  cropped_size: 60.0 # Length (in nm) of square cropped images (can take -1 for grain-sized box)
  save_cropped_grains: true # Options : true, false
dnatracing:
  run: true # Options : true, false
plotting:
  run: true # Options : true, false
  save_format: png # Options : see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html
  image_set: all  # Options : all, core
  zrange: [0, 4]  # low and high height range for core images (can take [null, null])
  colorbar: true  # Options : true, false
  axes: true # Options : true, false (due to off being a bool when parsed)
  cmap: nanoscope # Options : nanoscope, afmhot
  histogram_log_axis: false # Options : true, false
```
**Expected behavior**
The entire file name should be used to create those directories, instead of just the part before the period. For example, when processing a directory with `filename.01.spm` and `filename.02.spm`, directories `filename.01` and `filename.02` should be generated, instead of `filename`, and the error can then be avoided.

**Output**

If applicable please include the output error, this can be a copy and paste of the output (preferable) or a screenshot.
Output files can be attached to this bug report.

**(Not required if using Docker) Your computer configuration (please complete the following information):**
 - OS: windows 10
 - topostats version: 5bbf692
 - Python version: 3.9.12
 - Optionally, your installed packages: best way to get this is to paste the results of typing `pip freeze`.

**Additional context**
