### ISSUE TITLE
Introduce linting with Ruff

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#446]
A new Python linter [Ruff](https://github.com/charliermarsh/ruff) is available that is comparable to [flake8](https://flake8.pycqa.org/en/latest/) and [pylint](https://pylint.org). Its written in Rust and its main advantage is that its considerably quicker.

There is a [Language Server Protocol backend for Ruff](https://github.com/charliermarsh/ruff-lsp) to integrate with IDE's and a [Ruff pre-commit hook](https://github.com/charliermarsh/ruff-pre-commit) so integrating into current pipeline should be as easy as adding...

```yaml
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.191'
  hooks:
    - id: ruff
```

...to `.pre-commit-config.yaml` and making it a dependency under the `dev` section of `setup.cfg`.

Careful consideration as to the [configuration](https://github.com/charliermarsh/ruff#configuration) to ensure the same rules are applied will be required.

For now I think it would be wise to leave `pylint` and `flake8` in place too until we're happy it works and that there is parity.
