### ISSUE TITLE
CSV file structure breaks with some images

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#447]
**Describe the bug**
With some images, the file structure of the `folder_grainstats.csv` file breaks (incorrectly placed headers and commas). 

<img width="403" alt="image" src="https://user-images.githubusercontent.com/86117496/215493961-d17bd2e8-760d-400e-ba6d-a52d1a02e0d3.png">

I think this might be something to do with detection of grains but then subsequent removal before grainstats outputs data on them? I apologise for not looking into this further, as I don't have the time currently. I will come back to this to add information.

**To Reproduce**

- Run topostats with any config on the following set of `.spm` files in the following folder. https://drive.google.com/drive/folders/1dflIB-qEGMahmdLoVXwDC_dm9Xksnv1h

Note that the `folder_grainstats.csv` file is incorrectly formatted.

- Config file

```
base_dir: ./by_sample/A4
output_dir: ./by_sample/A4
#base_dir: ./raphael_difficult_input/A3_MgCl2_008
#output_dir: ./raphael_difficult_output/A3_MgCl2_008_tilt_first
#base_dir: ./comparisons/slide_2_blue
#output_dir: ./comparisons/slide_2_blue
warnings: ignore
cores: 6
quiet: false
file_ext: .spm
loading:
  channel: Height
filter:
  run: true # Options : true, false
  threshold_method: std_dev # Options : otsu, std_dev, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.3
  threshold_absolute:
    lower: -1.0
    upper: 1.0
#  gaussian_size: 1.0121397464510862 # in px
  gaussian_size: 0.5
  gaussian_mode: nearest
  remove_scars:
    run: true
    removal_iterations: 2
    threshold_low: 0.250
    threshold_high: 0.666
    max_scar_width: 4
    min_scar_length: 10
grains:
  run: true # Options : true, false
  # Thresholding by height
  threshold_method: std_dev # Options : std_dev, otsu, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    lower: 10.0
    upper: 1.3
  threshold_absolute:
    lower: -1.0
    upper: 1.0
  direction: upper # Options: upper, lower, both (defines whether to look for grains above or below thresholds or both)
  # Thresholding by area
  smallest_grain_size_nm2: 5000
  absolute_area_threshold:
    upper: [ 5000, 10000000 ] # above surface [Low, High] in nm^2 (also takes null)
    lower: [ null, null ] # below surface [Low, High] in nm^2 (also takes null)
grainstats:
  run: true # Options : true, false
  cropped_size: 500 # Length (in nm) of square cropped images (can take -1 for grain-sized box)
  save_cropped_grains: true # Options : true, false
dnatracing:
  run: true # Options : true, false
plotting:
  run: true # Options : true, false
  save_format: png # Options : see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html
  image_set: core  # Options : all, core
  zrange: [-3, 4]  # low and high height range for core images (can take [null, null])
  colorbar: true  # Options : true, false
  axes: true # Options : true, false (due to off being a bool when parsed)
  cmap: nanoscope # Options : nanoscope, afmhot
  mask_cmap: blu
  histogram_log_axis: false # Options : true, false
  histogram_bins: 200 # Number of bins for histogram plots to use

```

**Expected behavior**
A properly formatted output `csv` file.

**(Not required if using Docker) Your computer configuration (please complete the following information):**
 - OS: MacOS
 - topostats version: `main` commit: [c9a6fd9](https://github.com/AFM-SPM/TopoStats/commit/c9a6fd99c311c468e3f5783db78e17d74a140af7)
 - Python version: 3.10
