### ISSUE TITLE
Add pyupgrade to pre-commit

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#509]
[pyupgrade](https://github.com/asottile/pyupgrade) is a neat package to "_automatically upgrade syntax for newer versions of the language_". It includes a `pre-commit` hook which makes including and applying it to the existing code base relatively straight-forward.

Adding the following to `pre-commit-config.yaml` and committing the changes should bring about the changes.

```yaml
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
```

All modified files will need staging and committing and an addition should be made to `.git-blame-ignore-revs` to exclude the commits from blame as they are not substantial changes to the code base, rather syntax/linting.
