### ISSUE TITLE
Empty grains and filters folders produced when 'image_set' is 'core' 

### ISSUE THREAD

**Issue by derollins** [AFM-SPM/TopoStats#541]
## Describe the bug
When the 'image_set' field in the config file is set to 'core' and no images are produced in the grains or filters folder, these folders are still produced. This is annoying. 

## Include the configuration file.

If no configuration file was specified with the `-c`/`--config-file` option the defaults were used, please use the
`run_topostats --create-config-file crash.yaml` to save these to the `crash.yaml` file and copy the contents below.

``` 
# Sample configuration file auto-generated : 2023-04-25 17:25:56
base_dir: C:\Users\Work\OneDrive\Documents\Uni\Research\Data\My_Data\20230426_Sixfold
output_dir: C:\Users\Work\OneDrive\Documents\Uni\Research\Data\My_Data\20230426_Sixfold\output
log_level: info
cores: 3
file_ext: .spm
loading:
  channel: Height
filter:
  run: true
  row_alignment_quantile: 0.2
  threshold_method: std_dev
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    below: 10.0
    above: 1.0
  threshold_absolute:
    below: -1.0
    above: 1.0
  gaussian_size: 1.0121397464510862
  gaussian_mode: nearest
  remove_scars:
    run: true
    removal_iterations: 2
    threshold_low: 0.25
    threshold_high: 0.666
    max_scar_width: 4
    min_scar_length: 16
grains:
  run: true
  threshold_method: std_dev
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    below: 10.0
    above: 1.0
  threshold_absolute:
    below: -1.0
    above: 1.0
  direction: above
  smallest_grain_size_nm2: 50
  absolute_area_threshold:
    above:
    - 300
    - 3000
    below:
    - 
    - 
grainstats:
  run: true
  edge_detection_method: binary_erosion
  cropped_size: 40.0
dnatracing:
  run: true
plotting:
  run: true
  save_format: png
  image_set: core
  zrange:
  - -4
  - 4
  colorbar: true
  axes: true
  cmap: nanoscope
  mask_cmap: blu
  histogram_log_axis: false
  histogram_bins: 200
  dpi: 1000
summary_stats:
  run: true
  config:
```

## TopoStats version

Please report the version of TopoStats you are using. There are several ways of doing this, either with `pip` or
`run_topostats`. Please copy and paste all output from either of the following commands.

- `pip show topostats`
- `run_topostats --version`

```
Installed version of TopoStats : 2.0.0+341.ga429233
```

### Operating System

Please let us know what operating system you are using, if you have used more than one then tick all boxes.

* [X] Windows
* [ ] MacOS Intel (pre-2021)
* [ ] MacOS M1/M2 (post-2021)
* [ ] GNU/Linux (please include distribution)

### Python Version

Please let us know the version of Python you are using, paste the results of `python --version`

```
Python 3.10.9
```
