### ISSUE TITLE
Split config file into advanced and basic setting

### ISSUE THREAD

**Issue by derollins** [AFM-SPM/TopoStats#542]
**Is your feature request related to a problem? Please describe.**
Aid usability by splitting 'basic' functional settings and 'advanced' parameters.

**Describe the solution you'd like**

Here is my idea:
```
#Basic

base_dir: C:\Users\Work\OneDrive\Documents\Uni\Research\Data\My_Data\20230426_Sixfold
output_dir: C:\Users\Work\OneDrive\Documents\Uni\Research\Data\My_Data\20230426_Sixfold\output

file_ext: .spm
loading:
  channel: Height
filter:
  run: true
grains:
  run: true
grainstats:
  run: true

plotting:
  run: true
  save_format: png
  image_set: core
  zrange:
  - -4
  - 4
  colorbar: true
  axes: true
  cmap: nanoscope
summary_stats:
  run: true

---------------------------------------------------------------------------------------------------

#Advanced 

log_level: info
cores: 3
filter:
  row_alignment_quantile: 0.2
  threshold_method: std_dev
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    below: 10.0
    above: 1.0
  threshold_absolute:
    below: -1.0
    above: 1.0
  gaussian_size: 1.0121397464510862
  gaussian_mode: nearest
  remove_scars:
    run: true
    removal_iterations: 2
    threshold_low: 0.25
    threshold_high: 0.666
    max_scar_width: 4
    min_scar_length: 16
grains:
  threshold_method: std_dev
  otsu_threshold_multiplier: 1.0
  threshold_std_dev:
    below: 10.0
    above: 1.0
  threshold_absolute:
    below: -1.0
    above: 1.0
  direction: above
  smallest_grain_size_nm2: 50
  absolute_area_threshold:
    above:
    - 300
    - 3000
    below:
    - 
    - 
grainstats:
  edge_detection_method: binary_erosion
  cropped_size: 40.0
dnatracing:
  run: true
plotting:
  mask_cmap: blu
  histogram_log_axis: false
  histogram_bins: 200
  dpi: 1000
summary_stats:
  config:

```
**Additional context**
Discussed at Pyne group meeting 27/04/2023
