### ISSUE TITLE
Add pydocstyle to pre-commit hooks

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#660]
We can lint our docstrings using [pydocstyle](https://www.pydocstyle.org/en/stable/index.html).

Configuration can be added to `pyproject.toml` along the lines of..

```
[tool.pydocstyle]
convention = "numpy"
ignore = [
  "D101",
  "D2"
]
```

And to enable the hook would then require adding the following to `.pre-commit-config.yaml`

```yaml
    - repo  https://github.com/pycqa/pydocstyle
        rev: 6.3.0
        hooks:
        - id: pydocstyle
```
