### ISSUE TITLE
Add pydocstyle to pre-commit checks

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#663]
TopoStats already leverages [pre-commit](https://pre-commit.com) to lint code prior to commits.

We can improve the quality of our docstrings by adding [pydocstyle](https://www.pydocstyle.org/en/stable/) to the suite
of pre-commit hooks that are used.

This would involve adding the following hook to `.pre-commit-config.yaml`

``` yaml
    - repo  https://github.com/pycqa/pydocstyle
        rev: 6.3.0  # pick a git hash / tag to point to
        hooks:
        - id: pydocstyle
```

Whilst configuration can be done in the hook itself as documented we have the vast majority of our configuration in
`pyproject.toml` and `pydocstyle` supports this (see [docs](https://www.pydocstyle.org/en/stable/)). The following
section should therefore be added to `pyproject.toml`.

``` yaml
[tool.pydocstyle]
convention = "numpy"
match-dir = "topostats"
```

To ensure that `toml` support is included the following dependency requirement should also be added to `pyproject.toml`...

``` yaml
[project.optional-dependencies]
...
dev = [
  ...
  "pydocstyle[toml]"
  ...
]
```

It may then be worth running against all existing doc strings and addressing any issues that are thrown up, but this
should perhaps be a separate issue.
