### ISSUE TITLE
Restrict GitHub Pages building to PRs on main branch

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#838]
Currently our documentation isn't available and I think it is because the `.github/workflows/sphinx_docs_to_gh_pages.yaml` runs on any `push` to any branch it seems.

We should restrict this to only run on `pulls` to the `main` branch.

Switch the following...

```yaml
on:
  push:
    # Uncomment if only tagged releases are to have documentation built
    # tags:
    #   - v*
  workflow_dispatch: # Uncomment line if you also want to trigger action manually

```

...to...

```yaml
on:
  pull_requests:
    branches:
      - main
  workflow_dispatch:
```
