### ISSUE TITLE
Run CI on all pull requests not just `main`.

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#922]
Remove the restriction of running tests only on `main` branch.

### Currently

```yaml
name: Tests (pytest)

on:
  pull_request:
    branches:
      - main
```

### Should be

```yaml
name: Tests (pytest)

on:
  pull_request:
```
