### ISSUE TITLE
Run tests with `pre-commit` on only the changed/affected files using pytest-testmon.

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#923]
We should add a local job to `.pre-commit-config.yaml` to run `pytest` on only the files that have been changed or affected by changes using [`pytest-testmon`](https://github.com/tarpas/pytest-testmon/).

## `.pre-commit-config.yaml`

```yaml
  - repo: local
    hooks:
      - id: pytest-testmon
        args: ["--rcfile=.pylintrc"]
        name: Pytest Monitor
        entry: pytest 
        language: system
        files: \.py$
```

## `pyproject.toml`

Add `pytest-testmon` to the `tests` optional dependencies.

```toml
[project.optional-dependencies]
tests = [
  "pytest",
  "pytest-cov",
  "pytest-github-actions-annotate-failures",
  "pytest-mpl",
  "pytest-regtest",
  "pytest-testmon",
  "filetype",
]

```

## `docs/contributing.md`

Detail in the `docs/contributing.md` how to setup and use the `pytest-testmon` database on initially cloning the repository.

## `.gitignore`

Will probably have to ignore the `.testdatamon` from version control as it will be dependent on an individuals development stage.
